---
title: "Introduction to DS (сезон 2019)"
output:
  html_document: default
  pdf_document: default
lang: ru-RU
---

Это страничка с вводным курсом по анализу данных для менеджеров и маркетологов. Тут лежат все полезные материалы, которые только можно себе представить.


### Оценки и домашки

* Текущие оценки: [БММ-181,](https://docs.google.com/spreadsheets/d/e/2PACX-1vQzPkU-SVOzDX_LB-l0zlW_1u2XkWvrkUoub-UXNCL8sJexXU51kiHNSjH71Hm_rfmAXS86l0KlDfna/pubhtml?gid=144425580&single=true) [БММ-182,](https://docs.google.com/spreadsheets/d/e/2PACX-1vQzPkU-SVOzDX_LB-l0zlW_1u2XkWvrkUoub-UXNCL8sJexXU51kiHNSjH71Hm_rfmAXS86l0KlDfna/pubhtml?gid=5661136&single=true) [БММ-183,](https://docs.google.com/spreadsheets/d/e/2PACX-1vQzPkU-SVOzDX_LB-l0zlW_1u2XkWvrkUoub-UXNCL8sJexXU51kiHNSjH71Hm_rfmAXS86l0KlDfna/pubhtml?gid=218128335&single=true) [БММ-184](https://docs.google.com/spreadsheets/d/e/2PACX-1vQzPkU-SVOzDX_LB-l0zlW_1u2XkWvrkUoub-UXNCL8sJexXU51kiHNSjH71Hm_rfmAXS86l0KlDfna/pubhtml?gid=1636765882&single=true)
* [Небольшое видео про сдачу домашек,](https://yadi.sk/i/rVb_Nd7g8AmNog) мы теперь их сдаём в [anytask](https://anytask.org)

__Инвайты в [anytask:](https://anytask.org)__

```
                                БММ-181:   72K9PFp
                                БММ-182:   GEEVcYM
                                БММ-183:   o435scf
                                БММ-184:   NqlzJjj
                              
                                БМБ-181:   MzW5aVa
                                БМБ-182:   PrWvErL
                                БМБ-183:   mONMLoJ
                                БМБ-184:   Xl8GC0U
                                БМБ-185:   GMyKT1I
                                БМБ-186:   JXVDYv4
                                БМБ-187:   EB9O8Rk
                                БМБ-188:   3X0Nh77
```



### Домашние задания

Дедлайны по домашкам указаны в anytask. Для каждой группы свои. Для каждой домашки есть анонимная анкета, в которой вы можете высказать своё мнение о ней.

1. [Мини-дз 1: Введение в python](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_1%262_introduction/little_hw1_intro_to_python.zip)  [__Анонимка__](https://docs.google.com/forms/d/e/1FAIpQLSfI2niGkHtJMW0UEt0RiuDfLikkv9j0qjUicvHY-KkTpQqSkw/viewform)
2. [Мини-дз 2: Введение в pandas](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_1%262_introduction/little_hw2_intro_to_pandas.zip) [__Анонимка__](https://docs.google.com/forms/d/e/1FAIpQLSetSVMF7XRtdEHUp9duuoNofHSOnihr8PPOYUnEna6wqLGxSA/viewform)
3. [Мини-дз 3: Математика для ML](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_3_math/little_hw3_essential_maths.zip) [__Анонимка__](https://docs.google.com/forms/d/e/1FAIpQLSchfOV1ACGwQmZS2BtN-K39A81VoflcOVcGhxP1odqOIicVeA/viewform)
4. [Мини-дз 4: Основы статистики](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_4_matstat/little_hw4_matstat.zip) [__Анонимка__](https://docs.google.com/forms/d/e/1FAIpQLScXIVQNUJW03k76zB5RcOHX0iORIfV-d1-8_KQS4GcuKO5SoA/viewform)
5. [Мини-дз 5: Визуализация](https://nbviewer.jupyter.org/github/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_5_visual/little_hw5_visual.ipynb) [__Анонимка__](https://docs.google.com/forms/d/e/1FAIpQLSeQRtu8Xo5g6jDJ3zxgpfMuPa5cgi3igrne40_vqVZwYnDAZA/viewform)



### Лекции 

1. [Data Science: что это такое](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/lectures_bmm/Intro_to_DS.%20Lecture%201.pdf)
2. [Основы нужной математики](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/lectures_bmm/Intro_to_DS.%20Lecture%202.pdf)
3. [Описательные статистики](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/lectures_bmm/Intro_to_DS.%20Lecture%203.pdf)
4. [Учимся смотреть на данные](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/lectures_bmm/Intro_to_DS.%20Lecture%204.pdf)
5. Знакомимся с регрессией
6. Знакомимся с классификацией
7. KNN и деревья
8. Как принимать решение о внедрении (АБ, гипотезы)
9. Как расписать и обосновать продукт с применением машинного обучения
10. Кейсы машинного обучения в бизнесе: истории успехов и неудач
11. Приглашённый лектор 

> [Скачать все лекции, обожаю лекции!](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/lectures_bmm.zip)


-----------------------

### Логи семинаров

* [Датасет по vk](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/data/vk_main.csv)
* [Датасет по youtube](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/data/youtube_data.csv)

__Семинар 5 (визуализация)__

* [Скачать семинар](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_5_visual/sem_5.zip)
* [Посмотреть на питоновскую тетрадку с картинками](https://nbviewer.jupyter.org/github/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_5_visual/sem5_visualisation.ipynb)

__Семинар 4 (основы статистики)__

* [Скачать семинар](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_4_matstat/sem_4.zip)
* [Посмотреть ручные задачи](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_4_matstat/sem4_matstat.pdf)
* [Посмотреть на питонячью тетрадку с матстатом](https://nbviewer.jupyter.org/github/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_4_matstat/sem4_matstat.ipynb)

__Семинар 3 (математика для ML)__

* [Скачать семинар](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_3_math/sem_3.zip)
* [Посмотреть на питонячью тетрадку с математикой](https://nbviewer.jupyter.org/github/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_3_math/sem_3_essential_maths.ipynb)
* [Посмотреть на pdf с задачками](https://github.com/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_3_math/sem_3.pdf)

__Семинар 2 (вводимся в pandas)__

* [Скачать семинар](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_1%262_introduction/sem_2.zip)
* [Посмотреть на питонячью тетрадку с pandas](https://nbviewer.jupyter.org/github/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_1%262_introduction/sem2_pandas%20tutorial.ipynb)
* [Код, который мы писали прямо на семинаре](https://nbviewer.jupyter.org/github/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_1%262_introduction/sem2_pandas_on_seminar.ipynb)

__Семинар 1 (вводимся в python)__

* [Скачать семинар](https://github.com/FUlyankin/HSE_Data_Culture/raw/master/Intro_to_DS_2019/sem_1%262_introduction/sem_1.zip)
* [Посмотреть на тетрадку с введением в python](https://nbviewer.jupyter.org/github/FUlyankin/HSE_Data_Culture/blob/master/Intro_to_DS_2019/sem_1%262_introduction/sem1_introdution_python.ipynb)


### Большой план маленьких побед (семинаров):

1. Вводимся в python 
2. Продолжаем вводиться в python 
3. Математика для анализа данных
4. Введение в статистику 
5. Семинар по визуализациям
6. Регрессия 
7. Классификация 
8. На природу, в лес, к деревьям с соседями и кросс-валидацией!
9. Проверка гипотез, ручное введение в мастат
10. АБ-тесты, бутсрэп
11. Инструменты Google для поиска данных и решения прикладных задач
12. Кекс

__Опасности:__ 

* Самостоялки: 5 семинар - статистика, 7 - регрессия, 9 - классифкация, 11 - гипотезы и АБ-тесты. 
* На 12 семинаре будет кекс.
* Первое дз выдаётся после 5 семинара.
* Второе дз выдаётся после 11 семинара. 
* После практически каждого семинара вас ждёт маленькое дз


### Оценивание:

Накоп считается по формуле: 

$$
0.1 \cdot Datacamp + 0.1 \cdot \text{Задачи с семинаров} + 0.2 \cdot \text{самостоялки} + 0.2 \cdot \text{кекс} + 0.2 \cdot \text{дз1} + 0.2 \cdot \text{дз2}
$$

Итоговая оценка считается по формуле: 

$$
\max(0.7 \cdot \text{накоп} + 0.3 \cdot \text{экзамен};  0.5 \cdot \text{накоп} + 0.5 \cdot \text{экзамен})
$$

<br>

<br>

<br>








